services:

  lovvit-redem-logs:
    container_name: lovvit-redem-logs
    image: node:18
    volumes:
      - ./:/app
    command: npm run start
    ports:
      - 3000:3000
    restart: always

  mongo-db:
    container_name: mongo-db
    image: mongo
    volumes:
      - mydb:/data/db
    ports:
      - 27017:27017
    restart: "no"
    
volumes:
  mydb:
  
