version: "3"

services:
  
  mongoDB:
    container_name: mongoDB
    image: mongo:latest
    restart: always
    volumes:
      - mongodb-volcode:/data/db
    ports:
      - 27017:27017

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongoDB
    environment:
      - MONGO_URL=mongodb://mongoDB:27017/lovvitRedemLogs
    ports:
      - 9000:3000

volumes:
  mongodb-volcode: {}
